'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Language = 'en' | 'es';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    'app.title': 'HouseChurchApp',
    'app.subtitle': 'Network Management',
    'nav.dashboard': 'Dashboard',
    'nav.discipleship': '7&7 Discipleship',
    'nav.incubator': 'Pastor Incubator',
    'nav.churches': 'House Churches',
    'nav.members': 'Members',
    'nav.attendance': 'Attendance',
    'nav.prayer': 'Prayer Requests',
    'sidebar.user': 'User',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.createAccount': 'Create Account',
    'auth.creatingAccount': 'Creating account...',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.joinApp': 'Join HouseChurchApp',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.noAccount': "Don't have an account?",
    'auth.registerHere': 'Register here',
    'auth.hasAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    'auth.invalidCredentials': 'Invalid email or password.',
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 8 characters',
    'auth.registrationFailed': 'Registration failed. Please try again.',
    'auth.or': 'or',
    'auth.googleSignIn': 'Sign in with Google',
    'auth.googleSignUp': 'Sign up with Google',
    'dashboard.welcome': 'Welcome to HouseChurchApp',
    'dashboard.activeChurches': 'Active House Churches',
    'dashboard.totalMembers': 'Total Members',
    'dashboard.activePrayers': 'Active Prayer Requests',
    'dashboard.sub': 'Manage your house church network',
    'dashboard.recentPrayers': 'Recent Prayer Requests',
    'dashboard.loading': 'Loading...',
    'dashboard.error': 'Failed to load data. Please refresh.',
    'dashboard.anonymous': 'Anonymous',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.noResults': 'No results found',
    'coming.soon': 'Coming soon',
    'disc.title': '7&7 Discipleship',
    'disc.sub': '7 to Know, 7 to Grow — your journey through the foundations of faith',
    'disc.week': 'Week',
    'disc.day': 'Day',
    'disc.know': 'KNOW',
    'disc.grow': 'GROW',
    'disc.centralConcept': 'Central Concept',
    'disc.memoryVerses': 'Memory Verses',
    'disc.actionStep': 'Action Step',
    'disc.reflect': 'Reflect',
    'disc.apply': 'Apply',
    'disc.yourAnswer': 'Write your answer...',
    'disc.loading': 'Loading verse...',
    'disc.verseNote': 'Scripture text loaded from ESV Bible.',
    'disc.close': 'Close',
    'inc.title': 'Pastor Incubator',
    'inc.sub': 'House Church Pastor training — character, doctrine & convictions',
    'inc.week': 'Week',
    'inc.day': 'Day',
    'inc.module': 'Module',
    'inc.keyVerse': 'Key Verse',
    'inc.keyVerses': 'Key Verses',
    'inc.selfEval': 'Self-Evaluation',
    'inc.yourAnswer': 'Write your reflection...',
    'inc.section': 'Section',
    'inc.character': 'CHARACTER',
    'inc.doctrine': 'DOCTRINE',
    'inc.convictions': 'CONVICTIONS',
    'hc.title': 'House Churches',
    'hc.sub': 'Manage house church locations and groups',
    'hc.pastor': 'Pastor',
    'hc.host': 'Host',
    'hc.trainee': 'Pastor in Training',
    'hc.members': 'Members',
    'hc.back': 'Back to House Churches',
    'hc.location': 'Location',
    'hc.meetingTime': 'Meeting Time',
    'hc.phone': 'Phone',
    'hc.role': 'Role',
    'hc.create': 'Create House Church',
    'hc.edit': 'Edit House Church',
    'hc.name': 'House Church Name',
    'hc.description': 'Description',
    'hc.address': 'Address',
    'hc.street': 'Street',
    'hc.city': 'City',
    'hc.state': 'State',
    'hc.zip': 'ZIP Code',
    'hc.meetingDay': 'Meeting Day',
    'hc.selectMember': 'Select a member...',
    'hc.campus': 'Campus',
    'hc.allCampuses': 'All Campuses',
    'hc.noCampus': 'No Campus',
    'hc.noMembers': 'No members in this house church',
    'hc.viewDetails': 'View Details',
    'hc.created': 'House church created successfully.',
    'hc.updated': 'House church updated successfully.',
    'hc.createError': 'Failed to create house church.',
    'hc.updateError': 'Failed to update house church.',
    'common.name': 'Name',
    'role.admin': 'Admin',
    'role.house_church_pastor': 'House Church Pastor',
    'role.member': 'Member',
    'mem.title': 'Members',
    'mem.sub': 'Manage network members and contacts',
    'mem.search': 'Search by name or email...',
    'mem.addMember': 'Add Member',
    'mem.phone': 'Phone',
    'mem.showMinors': 'Show Minors',
    'mem.houseChurch': 'House Church',
    'mem.role': 'Role',
    'mem.gender': 'Gender',
    'mem.age': 'Age',
    'mem.birthday': 'Birthday',
    'mem.address': 'Address',
    'mem.showMap': 'Show Map',
    'mem.hideMap': 'Hide Map',
    'mem.noAddresses': 'No members with addresses to show on map. Sync from Planning Center to import addresses.',
    'pray.title': 'Prayer Requests',
    'pray.sub': 'Share and support each other in prayer',
    'pray.active': 'Active',
    'pray.answered': 'Answered',
    'pray.newRequest': 'New Request',
    'pray.markAnswered': 'Mark Answered',
    'pray.private': 'Private',
    'pray.submit': 'Submit',
    'pray.requestTitle': 'Title',
    'pray.requestDesc': 'Description',
    'pray.noRequests': 'No prayer requests yet',
    'att.title': 'Attendance',
    'att.sub': 'Track attendance for services and house churches',
    'att.eventType': 'Event Type',
    'att.sundayService': 'Sunday Service',
    'att.houseChurch': 'House Church',
    'att.date': 'Date',
    'att.present': 'Present',
    'att.save': 'Save Attendance',
    'att.saved': 'Attendance saved for {present} / {total} members.',
    'att.members': 'Members',
    'att.saveError': 'Failed to save attendance.',
    'pastoral.attendance': 'Attendance',
    'pastoral.sundayGathering': 'Sunday Gathering',
    'pastoral.houseChurchAttendance': 'House Church',
    'nav.pastoral': 'Pastoral Care',
    'pastoral.title': 'Pastoral Care',
    'pastoral.sub': 'Track 1:1 discipleship meetings with your members',
    'pastoral.logMeeting': 'Log Meeting',
    'pastoral.selectTopic': 'Select a topic',
    'pastoral.meetingDate': 'Meeting Date',
    'pastoral.notes': 'Notes',
    'pastoral.notesPlaceholder': 'What did you discuss? Any follow-ups?',
    'pastoral.save': 'Save Meeting',
    'pastoral.saving': 'Saving...',
    'pastoral.saved': 'Saved \u2713',
    'pastoral.meetingHistory': 'Meeting History',
    'pastoral.noMeetings': 'No meetings logged yet',
    'pastoral.addFlag': 'Add Flag',
    'pastoral.flagColor': 'Flag Color',
    'pastoral.flagDescription': 'Description',
    'pastoral.flagPlaceholder': 'What are you flagging?',
    'pastoral.yellow': 'Yellow \u2014 Monitor',
    'pastoral.red': 'Red \u2014 Urgent',
    'pastoral.resolve': 'Resolve',
    'pastoral.activeFlags': 'Active Flags',
    'pastoral.noFlags': 'No active flags',
    'pastoral.helperQuestions': 'Conversation Starters',
    'pastoral.suggestedVerses': 'Suggested Verses',
    'pastoral.lastContacted': 'Last Contacted',
    'pastoral.neverMet': 'Not yet',
    'pastoral.close': 'Close',
    'pastoral.prayerRequests': 'Prayer Requests',
    'pastoral.noPrayer': 'No active prayer requests',
    'pastoral.addPrayer': 'Add Prayer Request',
    'pastoral.noUserAccount': 'Prayer requests require a member app account.',
    'pastoral.notesLocked': 'Notes visible to author only',
    'pastoral.notesPrivate': 'Only visible to you',
    'pastoral.addNote': '+ Add Note',
    'pastoral.editNote': 'Edit',
    'pastoral.deleteNote': 'Delete',
    'pastoral.deleteNoteConfirm': 'Delete this note?',
    'pastoral.notePlaceholder': 'Write a note about this member...',
    'pastoral.noNotes': 'No notes yet',
    'pastoral.saveNote': 'Save Note',
    'pastoral.filterHC': 'House Church',
    'pastoral.searchMembers': 'Search members...',
    'hc.leadership': 'Leadership',
    'scripture.unavailable': 'Verse text unavailable. Please look up {ref} in your Bible.',
    'pray.visibility': 'Visibility',
    'pray.public': 'Public',
    'pray.houseChurch': 'House Church',
    'pray.privateLabel': 'Private (Pastor only)',
    'pray.statusActive': 'Active',
    'pray.statusAnswered': 'Answered',
    'pray.submitError': 'Failed to submit request. Please try again.',
    'pray.deleteConfirm': 'Delete permanently? This cannot be undone.',
    'pray.tabActive': 'Active',
    'pray.tabAnswered': 'Answered',
    'pray.forMyself': 'For Myself',
    'pray.forMember': 'On Behalf of Someone',
    'pray.onBehalfOf': 'On behalf of:',
    'pray.searchMember': 'Search member by name...',
    'pray.submittedBy': 'on behalf of',
    'nav.settings': 'Settings',
    'settings.title': 'Settings',
    'settings.sub': 'Manage user roles and permissions',
    'settings.manageRoles': 'User Roles',
    'settings.currentRole': 'Current Role',
    'settings.changeRole': 'Change Role',
    'settings.roleUpdated': 'Role updated successfully.',
    'settings.loadError': 'Failed to load users.',
    'settings.updateError': 'Failed to update role.',
    'settings.noPermission': 'Access Denied',
    'settings.adminOnly': 'Only Admins can manage user roles and permissions.',
    'settings.you': 'You',
    'settings.pcoTitle': 'Planning Center',
    'settings.pcoDesc': 'Sync members, campuses, and addresses from Planning Center.',
    'settings.pcoConnect': 'Connect Planning Center',
    'settings.pcoStatusConnected': 'Connected',
    'settings.pcoSync': 'Sync Members',
    'settings.pcoSyncing': 'Syncing...',
    'settings.pcoConnected': 'Planning Center connected successfully.',
    'settings.pcoError': 'Failed to connect Planning Center.',
    'settings.pcoSyncSuccess': 'Synced {imported} members, {campuses} campuses. {skipped} skipped (no email), {archived} archived. {total} total in PCO.',
    'settings.pcoImportError': 'Failed to sync members from Planning Center.',
  },
  es: {
    'app.title': 'HouseChurchApp',
    'app.subtitle': 'Gestión de Red',
    'nav.dashboard': 'Panel de Control',
    'nav.discipleship': 'Discipulado 7&7',
    'nav.incubator': 'Incubadora de Pastores',
    'nav.churches': 'Iglesias en Casa',
    'nav.members': 'Miembros',
    'nav.attendance': 'Asistencia',
    'nav.prayer': 'Peticiones de Oración',
    'sidebar.user': 'Usuario',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar Sesión',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signingIn': 'Iniciando sesión...',
    'auth.createAccount': 'Crear Cuenta',
    'auth.creatingAccount': 'Creando cuenta...',
    'auth.signInToAccount': 'Inicia sesión en tu cuenta',
    'auth.joinApp': 'Únete a HouseChurchApp',
    'auth.fullName': 'Nombre Completo',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.registerHere': 'Regístrate aquí',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.signInHere': 'Inicia sesión aquí',
    'auth.invalidCredentials': 'Correo o contraseña inválidos.',
    'auth.loginFailed': 'Error al iniciar sesión. Inténtalo de nuevo.',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.passwordTooShort': 'La contraseña debe tener al menos 8 caracteres',
    'auth.registrationFailed': 'Error al registrarse. Inténtalo de nuevo.',
    'auth.or': 'o',
    'auth.googleSignIn': 'Iniciar sesión con Google',
    'auth.googleSignUp': 'Registrarse con Google',
    'dashboard.welcome': 'Bienvenido a HouseChurchApp',
    'dashboard.activeChurches': 'Iglesias en Casa Activas',
    'dashboard.totalMembers': 'Miembros Totales',
    'dashboard.activePrayers': 'Peticiones de Oración Activas',
    'dashboard.sub': 'Administra tu red de iglesias en casa',
    'dashboard.recentPrayers': 'Peticiones de Oración Recientes',
    'dashboard.loading': 'Cargando...',
    'dashboard.error': 'Error al cargar datos. Por favor actualiza.',
    'dashboard.anonymous': 'Anónimo',
    'common.close': 'Cerrar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Añadir',
    'common.noResults': 'No se encontraron resultados',
    'coming.soon': 'Próximamente',
    'disc.title': '7&7 Discipulado',
    'disc.sub': '7 para Conocer, 7 para Crecer — tu camino por los fundamentos de la fe',
    'disc.week': 'Semana',
    'disc.day': 'Día',
    'disc.know': 'CONOCER',
    'disc.grow': 'CRECER',
    'disc.centralConcept': 'Concepto Central',
    'disc.memoryVerses': 'Versículos para Memorizar',
    'disc.actionStep': 'Acción a Seguir',
    'disc.reflect': 'Reflexiona',
    'disc.apply': 'Aplica',
    'disc.yourAnswer': 'Escribe tu respuesta...',
    'disc.loading': 'Cargando versículo...',
    'disc.verseNote': 'Texto bíblico cargado de la Biblia NBLA.',
    'disc.close': 'Cerrar',
    'inc.title': 'Incubadora de Pastores',
    'inc.sub': 'Formación de Pastores de Iglesia en Casa — carácter, doctrina y convicciones',
    'inc.week': 'Semana',
    'inc.day': 'Día',
    'inc.module': 'Módulo',
    'inc.keyVerse': 'Versículo Clave',
    'inc.keyVerses': 'Versículos Clave',
    'inc.selfEval': 'Autoevaluación',
    'inc.yourAnswer': 'Escribe tu reflexión...',
    'inc.section': 'Sección',
    'inc.character': 'CARÁCTER',
    'inc.doctrine': 'DOCTRINA',
    'inc.convictions': 'CONVICCIONES',
    'hc.title': 'Iglesias en Casa',
    'hc.sub': 'Administra ubicaciones y grupos de iglesias en casa',
    'hc.pastor': 'Pastor',
    'hc.host': 'Anfitrión',
    'hc.trainee': 'Pastor en Entrenamiento',
    'hc.members': 'Miembros',
    'hc.back': 'Volver a Iglesias en Casa',
    'hc.location': 'Ubicación',
    'hc.meetingTime': 'Horario de Reunión',
    'hc.phone': 'Teléfono',
    'hc.role': 'Rol',
    'hc.create': 'Crear Iglesia en Casa',
    'hc.edit': 'Editar Iglesia en Casa',
    'hc.name': 'Nombre de Iglesia en Casa',
    'hc.description': 'Descripción',
    'hc.address': 'Dirección',
    'hc.street': 'Calle',
    'hc.city': 'Ciudad',
    'hc.state': 'Estado',
    'hc.zip': 'Código Postal',
    'hc.meetingDay': 'Día de Reunión',
    'hc.selectMember': 'Seleccionar miembro...',
    'hc.campus': 'Campus',
    'hc.allCampuses': 'Todos los Campus',
    'hc.noCampus': 'Sin Campus',
    'hc.noMembers': 'No hay miembros en esta iglesia en casa',
    'hc.viewDetails': 'Ver Detalles',
    'hc.created': 'Iglesia en casa creada exitosamente.',
    'hc.updated': 'Iglesia en casa actualizada exitosamente.',
    'hc.createError': 'Error al crear iglesia en casa.',
    'hc.updateError': 'Error al actualizar iglesia en casa.',
    'common.name': 'Nombre',
    'role.admin': 'Administrador',
    'role.house_church_pastor': 'Pastor de Iglesia en Casa',
    'role.member': 'Miembro',
    'mem.title': 'Miembros',
    'mem.sub': 'Administra miembros y contactos de la red',
    'mem.search': 'Buscar por nombre o correo...',
    'mem.addMember': 'Añadir Miembro',
    'mem.phone': 'Teléfono',
    'mem.showMinors': 'Mostrar Menores',
    'mem.houseChurch': 'Iglesia en Casa',
    'mem.role': 'Rol',
    'mem.gender': 'Género',
    'mem.age': 'Edad',
    'mem.birthday': 'Cumpleaños',
    'mem.address': 'Dirección',
    'mem.showMap': 'Ver Mapa',
    'mem.hideMap': 'Ocultar Mapa',
    'mem.noAddresses': 'No hay miembros con direcciones para mostrar en el mapa. Sincroniza desde Planning Center para importar direcciones.',
    'pray.title': 'Peticiones de Oración',
    'pray.sub': 'Comparte y apóyense mutuamente en oración',
    'pray.active': 'Activas',
    'pray.answered': 'Contestadas',
    'pray.newRequest': 'Nueva Petición',
    'pray.markAnswered': 'Marcar Contestada',
    'pray.private': 'Privada',
    'pray.submit': 'Enviar',
    'pray.requestTitle': 'Título',
    'pray.requestDesc': 'Descripción',
    'pray.noRequests': 'No hay peticiones de oración aún',
    'att.title': 'Asistencia',
    'att.sub': 'Registra la asistencia de servicios e iglesias en casa',
    'att.eventType': 'Tipo de Evento',
    'att.sundayService': 'Servicio Dominical',
    'att.houseChurch': 'Iglesia en Casa',
    'att.date': 'Fecha',
    'att.present': 'Presentes',
    'att.save': 'Guardar Asistencia',
    'att.saved': 'Asistencia guardada para {present} / {total} miembros.',
    'att.members': 'Miembros',
    'att.saveError': 'Error al guardar la asistencia.',
    'pastoral.attendance': 'Asistencia',
    'pastoral.sundayGathering': 'Reuni\u00f3n Dominical',
    'pastoral.houseChurchAttendance': 'Iglesia en Casa',
    'nav.pastoral': 'Cuidado Pastoral',
    'pastoral.title': 'Cuidado Pastoral',
    'pastoral.sub': 'Registra reuniones 1:1 de discipulado con tus miembros',
    'pastoral.logMeeting': 'Registrar Reuni\u00f3n',
    'pastoral.selectTopic': 'Selecciona un tema',
    'pastoral.meetingDate': 'Fecha de la Reuni\u00f3n',
    'pastoral.notes': 'Notas',
    'pastoral.notesPlaceholder': '\u00bfQu\u00e9 discutieron? \u00bfHay seguimientos?',
    'pastoral.save': 'Guardar Reuni\u00f3n',
    'pastoral.saving': 'Guardando...',
    'pastoral.saved': 'Guardado \u2713',
    'pastoral.meetingHistory': 'Historial de Reuniones',
    'pastoral.noMeetings': 'A\u00fan no hay reuniones registradas',
    'pastoral.addFlag': 'Agregar Bandera',
    'pastoral.flagColor': 'Color de Bandera',
    'pastoral.flagDescription': 'Descripci\u00f3n',
    'pastoral.flagPlaceholder': '\u00bfQu\u00e9 est\u00e1s marcando?',
    'pastoral.yellow': 'Amarilla \u2014 Monitorear',
    'pastoral.red': 'Roja \u2014 Urgente',
    'pastoral.resolve': 'Resolver',
    'pastoral.activeFlags': 'Banderas Activas',
    'pastoral.noFlags': 'Sin banderas activas',
    'pastoral.helperQuestions': 'Para Comenzar la Conversaci\u00f3n',
    'pastoral.suggestedVerses': 'Vers\u00edculos Sugeridos',
    'pastoral.lastContacted': '\u00daltimo Contacto',
    'pastoral.neverMet': 'A\u00fan no',
    'pastoral.close': 'Cerrar',
    'pastoral.prayerRequests': 'Peticiones de Oraci\u00f3n',
    'pastoral.noPrayer': 'Sin peticiones de oraci\u00f3n activas',
    'pastoral.addPrayer': 'Agregar Petici\u00f3n de Oraci\u00f3n',
    'pastoral.noUserAccount': 'Las peticiones de oraci\u00f3n requieren una cuenta en la app.',
    'pastoral.notesLocked': 'Notas visibles solo para el autor',
    'pastoral.notesPrivate': 'Solo visible para ti',
    'pastoral.addNote': '+ Agregar Nota',
    'pastoral.editNote': 'Editar',
    'pastoral.deleteNote': 'Eliminar',
    'pastoral.deleteNoteConfirm': '\u00bfEliminar esta nota?',
    'pastoral.notePlaceholder': 'Escribe una nota sobre este miembro...',
    'pastoral.noNotes': 'A\u00fan no hay notas',
    'pastoral.saveNote': 'Guardar Nota',
    'pastoral.filterHC': 'Iglesia en Casa',
    'pastoral.searchMembers': 'Buscar miembros...',
    'hc.leadership': 'Liderazgo',
    'scripture.unavailable': 'Texto no disponible. Por favor busca {ref} en tu Biblia.',
    'pray.visibility': 'Visibilidad',
    'pray.public': 'P\u00fablico',
    'pray.houseChurch': 'Iglesia en Casa',
    'pray.privateLabel': 'Solo el Pastor',
    'pray.statusActive': 'Activa',
    'pray.statusAnswered': 'Contestada',
    'pray.submitError': 'Error al enviar la petición. Por favor intenta de nuevo.',
    'pray.deleteConfirm': '¿Eliminar permanentemente? Esto no se puede deshacer.',
    'pray.tabActive': 'Activas',
    'pray.tabAnswered': 'Contestadas',
    'pray.forMyself': 'Para Mí',
    'pray.forMember': 'En Nombre de Alguien',
    'pray.onBehalfOf': 'En nombre de:',
    'pray.searchMember': 'Buscar miembro por nombre...',
    'pray.submittedBy': 'en nombre de',
    'nav.settings': 'Configuraci\u00f3n',
    'settings.title': 'Configuraci\u00f3n',
    'settings.sub': 'Administra roles y permisos de usuarios',
    'settings.manageRoles': 'Roles de Usuarios',
    'settings.currentRole': 'Rol Actual',
    'settings.changeRole': 'Cambiar Rol',
    'settings.roleUpdated': 'Rol actualizado exitosamente.',
    'settings.loadError': 'Error al cargar usuarios.',
    'settings.updateError': 'Error al actualizar rol.',
    'settings.noPermission': 'Acceso Denegado',
    'settings.adminOnly': 'Solo los Administradores pueden administrar roles y permisos.',
    'settings.you': 'Tú',
    'settings.pcoTitle': 'Planning Center',
    'settings.pcoDesc': 'Sincroniza miembros, campus y direcciones desde Planning Center.',
    'settings.pcoConnect': 'Conectar Planning Center',
    'settings.pcoStatusConnected': 'Conectado',
    'settings.pcoSync': 'Sincronizar Miembros',
    'settings.pcoSyncing': 'Sincronizando...',
    'settings.pcoConnected': 'Planning Center conectado exitosamente.',
    'settings.pcoError': 'Error al conectar Planning Center.',
    'settings.pcoSyncSuccess': '{imported} miembros sincronizados, {campuses} campus. {skipped} omitidos (sin correo), {archived} archivados. {total} total en PCO.',
    'settings.pcoImportError': 'Error al sincronizar miembros desde Planning Center.',
  },
};

interface LangContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

function getInitialLanguage(): Language {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem('housechurch-lang');
    if (saved === 'en' || saved === 'es') return saved;
  }
  return 'en';
}

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setLanguageState(getInitialLanguage());
    setMounted(true);
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('housechurch-lang', lang);
    document.documentElement.lang = lang;
  }, []);

  useEffect(() => {
    if (mounted) {
      document.documentElement.lang = language;
    }
  }, [language, mounted]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LangContext);
  if (!context) {
    throw new Error('useLang must be used within LangProvider');
  }
  return context;
}
